default_context:
  category: general
  description: Generate table of contents in Markdown files based on headings
  git_base_url: https://github.com/jmknoble
  git_group: jmknoble
  git_project: markdown-toc
  git_url: https://github.com/jmknoble/markdown-toc
  package_name: markdown_toc
  project_name: markdown-toc
  project_type: python
  team_email: jmknoble@pobox.com
  team_name: jmknoble
  title: markdown-toc
  version: 0.2.2.post1
